-- Seed the service catalog from the existing UI mock data.
-- Safe to re-run (uses ON CONFLICT).

insert into service_categories (id, label, icon, sort_order) values
  ('transportation', 'Transportation', 'car', 1),
  ('home-help',     'Home Help',      'home', 2),
  ('errands',       'Errands',        'bag', 3),
  ('presence',      'Presence',       'user', 4),
  ('lifestyle',     'Lifestyle',      'heart', 5),
  ('business',      'Business',       'briefcase', 6)
on conflict (id) do update
  set label = excluded.label, icon = excluded.icon, sort_order = excluded.sort_order;

insert into services
  (id, category_id, title, blurb, base_price_cents, eta_label, popular, image_url, active)
values
  -- Transportation
  ('designated-driver', 'transportation', 'Designated Driver',
   'A licensed driver meets you and drives YOUR car home — ideal after drinks, late nights or long days.',
   2900, '20 min', true,
   'https://images.unsplash.com/photo-1532974297617-c0f05fe48bff?auto=format&fit=crop&w=800&q=70', true),
  ('motorcycle-taxi', 'transportation', 'Motorcycle Taxi',
   'A licensed motorcycle rider with a spare helmet beats traffic and gets you across the city in minutes.',
   1200, '10 min', false,
   'https://images.unsplash.com/photo-1568772585407-9361f9bf3a87?auto=format&fit=crop&w=800&q=70', true),
  ('car-battery-jump', 'transportation', 'Car Battery Jump',
   'A roadside helper arrives with cables and a portable jump pack to start your dead battery — no tow needed.',
   3500, '25 min', false,
   'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=70', true),

  -- Home Help
  ('furniture-assembly', 'home-help', 'Furniture Assembly',
   'A vetted handyperson assembles your flat-pack furniture — IKEA, beds, desks, dressers, shelves. Tools included.',
   5000, '30 min', false,
   'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=800&q=70', true),
  ('tv-mounting', 'home-help', 'TV Mounting',
   'Securely wall-mount any TV up to 85" on drywall, brick or concrete — mount bracket available on request.',
   6000, '30-45 min', false,
   'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=800&q=70', true),
  ('moving-help', 'home-help', 'Moving Help',
   'Two strong helpers for loading, unloading and heavy lifting — by the hour. Truck rental optional.',
   4000, 'Arrives in 30 min', false,
   'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=70', true),
  ('house-check-in', 'home-help', 'House Check-In',
   'Someone visits your home while you''re away — checks locks, waters plants, takes in mail, sends a photo report.',
   2000, '30 min', false,
   'https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=70', true),
  ('tech-setup', 'home-help', 'Tech Setup',
   'Set up your new TV, Wi-Fi, printer, smart home or migrate your old computer — every device, every brand.',
   4500, '45 min', false,
   'https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=800&q=70', true),
  ('maid-service', 'home-help', 'Maid Service',
   'Insured cleaner for dusting, vacuuming, kitchens, bathrooms and laundry — same cleaner can be re-booked weekly.',
   3500, 'Today', false,
   'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&w=800&q=70', true),
  ('appliance-repair', 'home-help', 'Appliance Repair',
   'Certified technician diagnoses and repairs fridges, dishwashers, washers, dryers and ovens — most fixed same day.',
   5500, 'Same day', false,
   'https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&fit=crop&w=800&q=70', true),

  -- Errands
  ('grocery-pickup', 'errands', 'Grocery Pickup',
   'We shop your grocery list at any store and deliver everything fresh to your door within an hour.',
   1500, '30-60 min', true,
   'https://images.unsplash.com/photo-1543168256-418811576931?auto=format&fit=crop&w=800&q=70', true),
  ('package-delivery', 'errands', 'Package Delivery',
   'Same-day local courier for documents, parcels and gifts — picked up and delivered door-to-door in under 90 minutes.',
   1200, '30 min', false,
   'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=70', true),
  ('package-return', 'errands', 'Package Return',
   'We pick up your unwanted online orders and drop them at UPS, FedEx, USPS or Amazon — tracking sent to your phone.',
   2000, '20-40 min', false,
   'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?auto=format&fit=crop&w=800&q=70', true),
  ('errand-runner', 'errands', 'Errand Runner',
   'Anything, anywhere — drop-offs, pickups, bank runs, post office, dry cleaning. Pay by the hour or by task.',
   2000, '20-40 min', false,
   'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=800&q=70', true),

  -- Presence
  ('wait-in-line', 'presence', 'Wait in Line',
   'Someone stands in line for you — DMV, passport office, restaurant, ticket release, sneaker drop. By the hour.',
   1500, 'Starts in 15 min', false,
   'https://images.unsplash.com/photo-1521791136064-7986c2920216?auto=format&fit=crop&w=800&q=70', true),
  ('listening-service', 'presence', 'Listening Service',
   'Talk to a trained listener for 30 or 60 minutes — no therapy, no advice, just full attention. In-person or video.',
   2000, 'Today', false,
   'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=800&q=70', true),
  ('sleep-call-companion', 'presence', 'Sleep Call Companion',
   'A companion stays on a quiet voice or video call while you fall asleep — for anxious sleepers and long-distance comfort.',
   1800, 'Tonight', false,
   'https://images.unsplash.com/photo-1455642305367-68834a1da7ab?auto=format&fit=crop&w=800&q=70', true),
  ('elder-assistance', 'presence', 'Elder Assistance',
   'Background-checked companion for seniors — grocery trips, doctor visits, conversation, light housekeeping.',
   2500, '45 min', false,
   'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=800&q=70', true),

  -- Lifestyle
  ('rent-a-friend', 'lifestyle', 'Rent-a-Friend',
   'Book a friendly local to hang out — explore the city, share a meal, attend an event or just talk over coffee.',
   2500, 'Today', false,
   'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=800&q=70', true),
  ('date-companion', 'lifestyle', 'Date Companion',
   'A poised platonic plus-one for dinners, weddings and family events. Fully professional, no romance involved.',
   4000, 'Today', false,
   'https://images.unsplash.com/photo-1495546968767-f0573cca821e?auto=format&fit=crop&w=800&q=70', true),
  ('event-companion', 'lifestyle', 'Event Companion',
   'Polished plus-one for galas, work parties or networking — dress code, talking points and exit time all coordinated.',
   5000, 'Schedule', false,
   'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=70', true),
  ('family-standin', 'lifestyle', 'Family Stand-in',
   'Trained actors play a parent, spouse or sibling — weddings, hospital visits, formal events. Discreet and rehearsed.',
   8000, 'Schedule', false,
   'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=800&q=70', true),
  ('wedding-guest', 'lifestyle', 'Wedding Guest',
   'Trained guests fill seats at your wedding — smile, applaud, take group photos. Rehearsed roles on request.',
   6000, 'Schedule', false,
   'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=800&q=70', true),
  ('professional-cuddler', 'lifestyle', 'Professional Cuddler',
   'Certified cuddlers offer non-sexual hugs, hand-holding and quiet company — clearly consented, fully clothed.',
   5000, 'Today', false,
   'https://images.unsplash.com/photo-1573497019418-b400bb3ab074?auto=format&fit=crop&w=800&q=70', true),
  ('shopping-companion', 'lifestyle', 'Shopping Companion',
   'A second opinion at the mall — fashion eye, carries bags, keeps you company. Personal stylists available for a premium.',
   2200, 'Today', false,
   'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=70', true),
  ('dog-walking', 'lifestyle', 'Dog Walking',
   'Vetted walker takes your dog out for 30 or 60 minutes — fresh water, treats, GPS-tracked route and photo update.',
   2000, 'Starts in 15 min', false,
   'https://images.unsplash.com/photo-1587300003388-59208cc962cb?auto=format&fit=crop&w=800&q=70', true),

  -- Business
  ('property-inspection', 'business', 'Property Inspection',
   'Verified inspector visits the property, photographs every room and emails you a full report — rentals, flips, due diligence.',
   6000, '60 min', false,
   'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=70', true)
on conflict (id) do update set
  title = excluded.title,
  blurb = excluded.blurb,
  base_price_cents = excluded.base_price_cents,
  eta_label = excluded.eta_label,
  popular = excluded.popular,
  image_url = excluded.image_url,
  category_id = excluded.category_id,
  active = excluded.active;
