/* Type definitions for our public schema rows.
 * Generated by hand to match supabase/migrations/0001_init.sql.
 * If schema drifts, regenerate via `supabase gen types typescript`. */

export type UserRole = "customer" | "provider" | "admin";
export type Country = "US" | "CA";
export type RequestStatus = "draft" | "matching" | "matched" | "cancelled" | "expired";
export type BookingStatus = "scheduled" | "in_progress" | "completed" | "cancelled" | "disputed";
export type ProviderStatus = "pending" | "approved" | "suspended" | "banned";
export type PaymentStatus = "pending" | "authorized" | "captured" | "refunded" | "partial_refund" | "failed";

export type Profile = {
  id: string;
  role: UserRole;
  full_name: string;
  phone: string | null;
  phone_verified: boolean;
  avatar_url: string | null;
  country: Country;
  default_locale: string;
  default_currency: string;
  default_timezone: string;
  created_at: string;
  updated_at: string;
};

export type CustomerProfile = {
  user_id: string;
  stripe_customer_id: string | null;
  default_address_id: string | null;
  wallet_balance_cents: number;
  referral_code: string | null;
};

export type ProviderProfile = {
  user_id: string;
  status: ProviderStatus;
  bio: string | null;
  languages: string[];
  service_radius_km: number;
  is_online: boolean;
  rating_avg: number | null;
  rating_count: number;
  tasks_completed: number;
  response_time_sec: number | null;
  stripe_connect_account_id: string | null;
  stripe_identity_verification_id: string | null;
  background_check_id: string | null;
  background_check_status: string | null;
  id_verified_at: string | null;
  background_verified_at: string | null;
  approved_at: string | null;
  approved_by: string | null;
  insurance_active_until: string | null;
  rejection_reason: string | null;
  created_at: string;
};

export type ServiceCategory = {
  id: string;
  label: string;
  icon: string;
  sort_order: number;
  active: boolean;
};

export type Service = {
  id: string;
  category_id: string;
  title: string;
  blurb: string;
  base_price_cents: number;
  eta_label: string | null;
  countries: Country[];
  popular: boolean;
  image_url: string | null;
  active: boolean;
  created_at: string;
};

export type Address = {
  id: string;
  user_id: string;
  label: string | null;
  formatted: string;
  city: string | null;
  region: string | null;
  country: Country | null;
  postal_code: string | null;
  // PostGIS geography(Point, 4326). Serialized as WKT/GeoJSON depending on
  // the query; treated as opaque on the TS side since we never read coords
  // app-side (all proximity math runs in SQL via find_nearby_providers).
  location: unknown;
  created_at: string;
};

export type Request = {
  id: string;
  customer_id: string;
  service_id: string;
  pickup_address_id: string | null;
  dropoff_address_id: string | null;
  scheduled_for: string | null;
  notes: string | null;
  estimated_price_cents: number | null;
  estimated_duration_min: number | null;
  status: RequestStatus;
  created_at: string;
};

export type Booking = {
  id: string;
  request_id: string | null;
  customer_id: string;
  provider_id: string;
  service_id: string;
  status: BookingStatus;
  scheduled_for: string | null;
  started_at: string | null;
  completed_at: string | null;
  cancelled_at: string | null;
  cancel_reason: string | null;
  base_price_cents: number;
  distance_cents: number;
  service_fee_cents: number;
  tip_cents: number;
  total_cents: number;
  platform_fee_cents: number;
  payout_cents: number;
  currency: string;
  stripe_payment_intent_id: string | null;
  payment_status: PaymentStatus;
  created_at: string;
};

export type Conversation = {
  id: string;
  booking_id: string | null;
  customer_id: string;
  provider_id: string;
  last_message_at: string;
  created_at: string;
};

export type Message = {
  id: string;
  conversation_id: string;
  sender_id: string;
  body: string | null;
  attachment_url: string | null;
  read_by_recipient_at: string | null;
  created_at: string;
};

export type Notification = {
  id: string;
  user_id: string;
  type: string;
  payload: Record<string, unknown>;
  read_at: string | null;
  created_at: string;
};
